"""Added start and end time for games

Revision ID: e27b750d946c
Revises: ebec477e29e9
Create Date: 2025-10-20 18:15:15.062018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e27b750d946c'
down_revision: Union[str, None] = 'ebec477e29e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('game', sa.Column('ended_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'ended_at')
    op.drop_column('game', 'started_at')
    # ### end Alembic commands ###
