/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/layout/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BottomNav: typeof import('./components/layout/BottomNav.vue')['default']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    GoalsList: typeof import('./components/match/GoalsList.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoadingSpinner: typeof import('./components/common/LoadingSpinner.vue')['default']
    MatchCard: typeof import('./components/match/MatchCard.vue')['default']
    MatchScoreboard: typeof import('./components/match/MatchScoreboard.vue')['default']
    PlayerCard: typeof import('./components/player/PlayerCard.vue')['default']
    PlayerSearchDialog: typeof import('./components/player/PlayerSearchDialog.vue')['default']
    PlayerStatsCard: typeof import('./components/player/PlayerStatsCard.vue')['default']
    RecordGoalDialog: typeof import('./components/match/RecordGoalDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamLineup: typeof import('./components/match/TeamLineup.vue')['default']
  }
}
