FROM public.ecr.aws/lambda/python:3.9.2025.11.23.14

COPY backend/main/requirements.prod.txt ./requirements.prod.txt

RUN pip3 install --no-cache-dir --upgrade pip && \
    pip3 install --no-cache-dir -r requirements.prod.txt

COPY backend/main/app/ ./app
COPY logging.yaml /logging/logging.yaml

CMD [ "app.main.handler" ]